# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Synth 8-3331}  -suppress 
set_msg_config  -id {IP_Flow 19-3153}  -suppress 
set_msg_config  -id {IP_Flow 19-2207}  -suppress 
set_msg_config  -id {IP_Flow 19-5463}  -suppress 
set_msg_config  -id {IP_Flow 19-5462}  -suppress 
set_msg_config  -id {IP_Flow 19-3480}  -suppress 
set_msg_config  -id {IP_Flow 19-1965}  -suppress 
set_msg_config  -id {Synth 8-3295}  -suppress 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.cache/wt [current_project]
set_property parent.project_path F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths {
  f:/DAKSHA/CommSrcs/FPGA/ip_repo/CZT_SPI_Comm_1.0
  f:/DAKSHA/CommSrcs/FPGA/ip_repo/CZT_SPI_Comm_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/new/CZT_SPI_Comm.vhd
  F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/new/Serial_to_Parallel.vhd
  F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/new/Time_Stamp.vhd
  F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/hdl/BD_wo_axi_wrapper.vhd
}
add_files F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/BD_wo_axi.bd
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_processing_system7_0_0/BD_wo_axi_processing_system7_0_0.xdc]
set_property used_in_synthesis false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_clock_converter_0_0/BD_wo_axi_axi_clock_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_clock_converter_0_0/BD_wo_axi_axi_clock_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_clock_converter_0_0/BD_wo_axi_axi_clock_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_fifo_generator_0_0/BD_wo_axi_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_fifo_generator_0_0/BD_wo_axi_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_proc_sys_reset_0_0/BD_wo_axi_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_proc_sys_reset_0_0/BD_wo_axi_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_0/BD_wo_axi_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_0/BD_wo_axi_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_0/BD_wo_axi_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_1/BD_wo_axi_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_1/BD_wo_axi_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_1/BD_wo_axi_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_1_1/BD_wo_axi_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_1_1/BD_wo_axi_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_1_1/BD_wo_axi_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_Cmd_Out_0/BD_wo_axi_Cmd_Out_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_Cmd_Out_0/BD_wo_axi_Cmd_Out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_Cmd_Out_0/BD_wo_axi_Cmd_Out_0.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_WR_Req_Out_0/BD_wo_axi_WR_Req_Out_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_WR_Req_Out_0/BD_wo_axi_WR_Req_Out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_WR_Req_Out_0/BD_wo_axi_WR_Req_Out_0.xdc]
set_property used_in_synthesis false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/BD_wo_axi_ila_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_ila_0_2/BD_wo_axi_ila_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/ip/BD_wo_axi_auto_pc_0/BD_wo_axi_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/sources_1/bd/BD_wo_axi/BD_wo_axi_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/constrs_1/new/Zybo_Board_Constrs.xdc
set_property used_in_implementation false [get_files F:/DAKSHA/CommSrcs/FPGA/CZT/CZT.srcs/constrs_1/new/Zybo_Board_Constrs.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top BD_wo_axi_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BD_wo_axi_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file BD_wo_axi_wrapper_utilization_synth.rpt -pb BD_wo_axi_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
