# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo_Board_Constrs.xdc

# Block Designs: bd/BD_wo_axi/BD_wo_axi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi || ORIG_REF_NAME==BD_wo_axi} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_processing_system7_0_0/BD_wo_axi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_processing_system7_0_0 || ORIG_REF_NAME==BD_wo_axi_processing_system7_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_axi_clock_converter_0_0/BD_wo_axi_axi_clock_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_clock_converter_0_0 || ORIG_REF_NAME==BD_wo_axi_axi_clock_converter_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_fifo_generator_0_0/BD_wo_axi_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_fifo_generator_0_0 || ORIG_REF_NAME==BD_wo_axi_fifo_generator_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_proc_sys_reset_0_0/BD_wo_axi_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_proc_sys_reset_0_0 || ORIG_REF_NAME==BD_wo_axi_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_CZT_SPI_Comm_0_0/BD_wo_axi_CZT_SPI_Comm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_CZT_SPI_Comm_0_0 || ORIG_REF_NAME==BD_wo_axi_CZT_SPI_Comm_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_Serial_to_Parallel_0_0/BD_wo_axi_Serial_to_Parallel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_Serial_to_Parallel_0_0 || ORIG_REF_NAME==BD_wo_axi_Serial_to_Parallel_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_Time_Stamp_0_0/BD_wo_axi_Time_Stamp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_Time_Stamp_0_0 || ORIG_REF_NAME==BD_wo_axi_Time_Stamp_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_xlconcat_0_0/BD_wo_axi_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_xlconcat_0_0 || ORIG_REF_NAME==BD_wo_axi_xlconcat_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_xbar_0/BD_wo_axi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_xbar_0 || ORIG_REF_NAME==BD_wo_axi_xbar_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_axi_interconnect_0_0/BD_wo_axi_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_interconnect_0_0 || ORIG_REF_NAME==BD_wo_axi_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_0/BD_wo_axi_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_0_0 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_0_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_1/BD_wo_axi_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_0_1 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_0_1} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_1_1/BD_wo_axi_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_1_1 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_1_1} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_Cmd_Out_0/BD_wo_axi_Cmd_Out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_Cmd_Out_0 || ORIG_REF_NAME==BD_wo_axi_Cmd_Out_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_WR_Req_Out_0/BD_wo_axi_WR_Req_Out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_WR_Req_Out_0 || ORIG_REF_NAME==BD_wo_axi_WR_Req_Out_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/BD_wo_axi_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_system_ila_0_0 || ORIG_REF_NAME==BD_wo_axi_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/bd_0/bd_abc7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_abc7 || ORIG_REF_NAME==bd_abc7} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/bd_0/ip/ip_0/bd_abc7_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_abc7_ila_lib_0 || ORIG_REF_NAME==bd_abc7_ila_lib_0} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/BD_wo_axi_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_ila_0_1 || ORIG_REF_NAME==BD_wo_axi_ila_0_1} -quiet] -quiet

# IP: bd/BD_wo_axi/ip/BD_wo_axi_auto_pc_0/BD_wo_axi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_wo_axi_auto_pc_0 || ORIG_REF_NAME==BD_wo_axi_auto_pc_0} -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_processing_system7_0_0/BD_wo_axi_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_processing_system7_0_0 || ORIG_REF_NAME==BD_wo_axi_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_clock_converter_0_0/BD_wo_axi_axi_clock_converter_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_clock_converter_0_0 || ORIG_REF_NAME==BD_wo_axi_axi_clock_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_clock_converter_0_0/BD_wo_axi_axi_clock_converter_0_0_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_fifo_generator_0_0/BD_wo_axi_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_fifo_generator_0_0 || ORIG_REF_NAME==BD_wo_axi_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_fifo_generator_0_0/BD_wo_axi_fifo_generator_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_fifo_generator_0_0 || ORIG_REF_NAME==BD_wo_axi_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_proc_sys_reset_0_0/BD_wo_axi_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_proc_sys_reset_0_0 || ORIG_REF_NAME==BD_wo_axi_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_proc_sys_reset_0_0/BD_wo_axi_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_proc_sys_reset_0_0 || ORIG_REF_NAME==BD_wo_axi_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_0/BD_wo_axi_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_0_0 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_0/BD_wo_axi_axi_gpio_0_0_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_0/BD_wo_axi_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_0_0 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_1/BD_wo_axi_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_0_1 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_1/BD_wo_axi_axi_gpio_0_1_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_0_1/BD_wo_axi_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_0_1 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_1_1/BD_wo_axi_axi_gpio_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_1_1 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_1_1/BD_wo_axi_axi_gpio_1_1_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_axi_gpio_1_1/BD_wo_axi_axi_gpio_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_axi_gpio_1_1 || ORIG_REF_NAME==BD_wo_axi_axi_gpio_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_Cmd_Out_0/BD_wo_axi_Cmd_Out_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_Cmd_Out_0 || ORIG_REF_NAME==BD_wo_axi_Cmd_Out_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_Cmd_Out_0/BD_wo_axi_Cmd_Out_0_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_Cmd_Out_0/BD_wo_axi_Cmd_Out_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_Cmd_Out_0 || ORIG_REF_NAME==BD_wo_axi_Cmd_Out_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_WR_Req_Out_0/BD_wo_axi_WR_Req_Out_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_WR_Req_Out_0 || ORIG_REF_NAME==BD_wo_axi_WR_Req_Out_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_WR_Req_Out_0/BD_wo_axi_WR_Req_Out_0_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_WR_Req_Out_0/BD_wo_axi_WR_Req_Out_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_WR_Req_Out_0 || ORIG_REF_NAME==BD_wo_axi_WR_Req_Out_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_abc7_ila_lib_0 || ORIG_REF_NAME==bd_abc7_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_abc7_ila_lib_0 || ORIG_REF_NAME==bd_abc7_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/bd_0/ip/ip_0/bd_abc7_ila_lib_0_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/bd_0/bd_abc7_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_system_ila_0_0/BD_wo_axi_system_ila_0_0_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_ila_0_1 || ORIG_REF_NAME==BD_wo_axi_ila_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_wo_axi_ila_0_1 || ORIG_REF_NAME==BD_wo_axi_ila_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_ila_0_1/BD_wo_axi_ila_0_1_ooc.xdc

# XDC: bd/BD_wo_axi/ip/BD_wo_axi_auto_pc_0/BD_wo_axi_auto_pc_0_ooc.xdc

# XDC: bd/BD_wo_axi/BD_wo_axi_ooc.xdc
